eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true # 注册到eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 3 # 服务发现 拉取 ReadOnly缓存 间隔默认为 30s
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 3 # 心跳间隔, 告诉服务端自己还存活, 默认30s
    lease-expiration-duration-in-seconds: 9 # 告诉服务端时间内没有收到心跳就证明服务挂掉, 默认90s

spring:
  application:
    name: eureka-consumer
  cloud:
    loadbalancer:
      retry:
        # 在RetryLoadBalancerInterceptor里面为RetryTemplate注入重试器, 需要添加spring retry依赖
        # 和下面的ribbon重试没有关系
        enabled: true
server:
  port: 8082
feign:
  client:
    config:
      default:
        read-timeout: 30000
        connect-timeout: 30000
