eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true # 注册到eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 3 # 服务发现 拉取 ReadOnly缓存 间隔默认为 30s
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 3 # 心跳间隔, 告诉服务端自己还存活, 默认30s
    lease-expiration-duration-in-seconds: 9 # 告诉服务端时间内没有收到心跳就证明服务挂掉, 默认90s

spring:
  application:
    name: eureka-consumer
server:
  port: 8082
feign:
  client:
    config:
      default:
        read-timeout: 30000
        connect-timeout: 30000

# https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html#_customizing_the_ribbon_client_by_setting_properties
eureka-provider:
  ribbon:
    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.DummyPing
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NIWSServerListFilterClassName: org.springframework.cloud.netflix.ribbon.ZonePreferenceServerListFilter

