spring:
  application:
    name: ahao-rocketmq


rocketmq.name-server: 192.168.19.131:9876
rocketmq.producer.namespace: ahao-namespace
rocketmq.producer.group: ahao-producer-group
rocketmq.consumer.namespace: ahao-namespace
