version: "3.8"

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: xxl-job-admin
    restart: on-failure
    ports:
      # 避免8080端⼝冲突, 配置宿主机映射端⼝为8090
      - "8090:8080"
    networks:
      - ahaonet
    environment:
      # https://github.com/xuxueli/xxl-job/issues/1650
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&rewriteBatchedStatements=true
      --spring.datasource.username=root
      --spring.datasource.password=root"
networks:
  ahaonet:
    name: ahaonet
    driver: bridge
# docker-compose -f docker-compose-xxljob.yml up -d
