# 可配置属性: com.netflix.client.config.CommonClientConfigKey

spring:
  cloud:
    loadbalancer:
      retry:
        # 在RetryLoadBalancerInterceptor里面为RetryTemplate注入重试器, 需要添加spring retry依赖
        # 和下面的ribbon重试没有关系
        enabled: true

# 针对 service1 服务的配置
service1:
  ribbon:
    listOfServers: http://www.baidu.com:80/, http://cn.bing.com:80/
    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.DummyPing
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NIWSServerListFilterClassName: org.springframework.cloud.netflix.ribbon.ZonePreferenceServerListFilter
# 全局配置
ribbon:
  eager-load:
    enabled: true
  # LoadBalancerCommand.execute 方法中读取
  ReadTimeout: 1000
  # LoadBalancerCommand.execute 方法中读取
  ConnectTimeout: 1000
  GZipPayload: true
  # FeignLoadBalancer.getRequestSpecificRetryHandler 方法中读取, 无论请求的什么时候有异常, 都会触发重试
  OkToRetryOnAllOperations: true
  # 同一台实例最大重试次数, RequestSpecificRetryHandler 构造函数中读取
  MaxAutoRetries: 1
  # 最多允许切换多少台实例, RequestSpecificRetryHandler 构造函数中读取
  MaxAutoRetriesNextServer: 1
