# https://docs.gitlab.cn/jh/install/docker.html
version: "3.8"
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    restart: on-failure
    ports:
      - "2080:80"
      - "2443:443"
      - "1022:22"
      # 修改默认的ssh端口后, 要指定端口, ssh -T git@gitlab.ahao.moe -p 1022, git clone ssh://git@gitlab.ahao.moe:1022/ahao/ahao-commerce.git
    environment:
      GITLAB_ROOT_PASSWORD: "rootroot"
    volumes:
      - /opt/gitlab/config:/etc/gitlab    # 用于存储 GitLab 配置文件
      - /opt/gitlab/logs:/var/log/gitlab  # 用于存储日志
      - /opt/gitlab/data:/var/opt/gitlab  # 用于存储应用程序数据
    shm_size: '256m'  # https://docs.gitlab.com/ee/install/docker.html#devshm-mount-not-having-enough-space-in-docker-container
    networks:
      - ahaonet
  jenkins:
    # 密码: docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword
    image: jenkins/jenkins:lts-centos7-jdk8 # 2.357 之后不再支持jdk8, https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-masters/maven-jobs-and-java-versions-compatibility
    container_name: jenkins
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker           # 解决docker命令找不到的问题
      - /var/run/docker.sock:/var/run/docker.sock # 容器内访问外部docker daemon, TODO 解决权限问题(太暴力了): chmod a+rw /var/run/docker.sock
    networks:
      - ahaonet
  sonarqube:
    image: sonarqube:7.8-community # 7.8 之后不再支持jdk8和Mysql, https://docs.sonarqube.org/7.8/requirements/requirements/
    container_name: sonarqube
    depends_on:
      - db
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      # 默认是h2数据库, CREATE DATABASE sonar DEFAULT CHARACTER SET utf8;
      SONARQUBE_JDBC_URL: jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: root
      # 默认用户名admin、密码admin
    volumes:
      - sonarqube-data:/opt/sonarqube/data              # 数据文件
      - sonarqube-logs:/opt/sonarqube/logs              # 日志文件
      - sonarqube-extensions:/opt/sonarqube/extensions  # 扩展文件, 如汉化插件：https://github.com/xuhuisheng/sonar-l10n-zh
    networks:
      - ahaonet
  db:
    image: mysql:5.7
    container_name: devops_db
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    networks:
      - ahaonet
    volumes:
      - /etc/mysql
      - /var/lib/mysql
      - /var/log/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb_buffer_pool_size=64M' ]
networks:
  ahaonet:
    name: ahaonet
    driver: bridge
volumes:
  jenkins-data: # https://github.com/jenkinsci/docker/issues/493
  # 只允许使用内置volume, 不允许使用外部目录, https://docs.sonarqube.org/latest/setup/install-server/#header-3
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
# docker-compose -f docker-compose-devops.yml up -d
