### 在accounts这个index下创建type为person, id为1的记录
POST {{host}}/accounts/person/1
Content-Type: application/json

{"name": "John", "lastname": "Doe", "job_description": "System Admin"}

### 在accounts这个index下创建type为person, id为1的记录
POST {{host}}/accounts/person/1/_update
Content-Type: application/json

{"doc": {"job_description": "new System Admin"}}

### 查询accounts这个index下, type为person, id为1的记录
GET {{host}}/accounts/person/1
### 查询accounts这个index下, type为person, 根据关键字搜索
GET {{host}}/accounts/person/_search?q=john
### 查询accounts这个index下, type为person, 根据关键字搜索
GET {{host}}/accounts/person/_search
Content-Type: application/json

{"query": {"match": {"name": "john"}}}

### 在accounts这个index下删除type为person, id为1的记录
DELETE {{host}}/accounts/person/1
### 删除accounts这个index
DELETE {{host}}/accounts

### 批量发送请求_bulk
POST {{host}}/_bulk

### 批量查询
GET {{host}}/_mget
Content-Type: application/json

{"docs": [{"_index": "accounts", "_type": "person", "_id": "1"}, {"_index": "accounts", "_type": "person", "_id": "2"}]}

### 分词API
POST {{host}}/_analyze
Content-Type: application/json

{"analyzer": "standard", "text": "hello world!"}
