### 查询所有索引所有文档
GET {{eshost}}/_search
### 查询account索引所有文档
GET {{eshost}}/account/_search
### 查询index1和index2索引所有文档
GET {{eshost}}/index1,index2/_search
### 使用通配符查询索引下的所有文档
GET {{eshost}}/account*/_search

### 使用 uri 的形式查询, 查询 account 索引下 name 字段包含 hello 的所有 document, 按照 name 字段升序
GET {{eshost}}/account/_search?q=name:hello&sort=name:asc

### 使用 DSL 的形式查询, 查询 account 索引下的所有 document
GET {{eshost}}/account/_search
Content-Type: application/json

{
    "query": {
        "match_all": {}
    }
}

### 使用 DSL 的形式查询, 查询 account 索引下 name 字段包含 hello 的所有 document, 按照 name 字段升序
GET {{eshost}}/account/_search
Content-Type: application/json

{
    "query": {
        "match": {
            "name": "hello"
        }
    },
    "sort": [
        {
            "name": "asc"
        }
    ]
}

### 使用 DSL 的形式查询, 分页查询 account 索引下的所有 document, 从第1条开始查, 查2条数据
GET {{eshost}}/account/_search
Content-Type: application/json

{
    "query": {
        "match_all": {}
    },
    "from": 1,
    "size": 2
}

### 使用 DSL 的形式查询, 查询 account 索引下的所有 document 的 name 字段
GET {{eshost}}/account/_search
Content-Type: application/json

{
    "query": {
        "match_all": {}
    },
    "_source": ["name"]
}

### 使用 DSL 的形式查询, 查询 account 索引下 name 字段包含 hello 且 age 大于25 的document
GET {{eshost}}/account/_search
Content-Type: application/json

{
    "query": {
        "bool": {
            "must": {
                "match": {
                    "name": "hello"
                }
            }
        }
    },
    "_filter": {
        "range": {
            "age": {"gt": 25}
        }
    }
}

### 使用 DSL 的形式查询, 查询 account 索引下 name 字段包含 hello 的所有 document
GET {{eshost}}/account/_search
Content-Type: application/json

{
  "query": {
    "term": {"name": "hello"}
  }
}
