# 服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: 127.0.0.1
spring:
  application:
    name: hystrix
server:
  port: 8080

# 启动 hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        read-timeout: 30000
        connect-timeout: 30000

# com.netflix.hystrix.HystrixCommandProperties
# 隔离线程超时时间，默认1s
hystrix.command:
  default:
    execution:
      isolation.thread.timeoutInMilliseconds: 1000
      circuitBreaker:
        # 一定时间内，如果经过断路器的流量不超过20次，那也没必要去开启断路器，默认是20
        requestVolumeThreshold: 20
  EUREKA-SERVER:
    execution.isolation.thread.timeoutInMilliseconds: 1000
