spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlXADataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/ahaodb?useSSL=false
    username: root
    password: root

  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager
