spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlXADataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahaodb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: root

  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager
