spring:
  application:
    # 这里的name要和seata.vgroup-mapping的key保持一致
    name: ahao-seata
  datasource:
    url: jdbc:mysql://${MYSQL_URL}/ahaodb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false&rewriteBatchedStatements=true&useAffectedRows=true
    username: root
    password: root

seata:
  enabled: true
  # 当前应用的事务分组
  tx-service-group: ahao-seata-tx-group
  service:
    vgroup-mapping:
      # 根据事务分组, 去找到TC集群名称
      # 这里的key要和seata.service.tx-service-group保持一致
      ahao-seata-tx-group: default
    grouplist:
      # 根据TC集群名称, 去找到TC服务地址
      # 这里的key要和seata.service.vgroup-mapping的value保持一致
      default: 192.168.19.128:8091
