spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_URL}/ahaodb?useSSL=false
      username: root
      password: root

      # 连接测试, 会降低性能
      test-on-borrow: false        # 申请连接时执行 validationQuery 检测连接是否有效
      test-on-return: false        # 归还连接时执行validationQuery检测连接是否有效
      test-while-idle: true        # 申请连接时, 如果空闲时间大于 time-between-eviction-runs-millis, 则执行 validation-query 判断连接是否有效
