################################################## Redis 配置 ##################################################
spring.redis.host: localhost
spring.redis.port: 6379
spring.redis.database: 0
spring.redis.password:
spring.redis.timeout: 10000     # 连接超时时间（毫秒）
spring.redis.jedis.pool.max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait: 1200ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-idle: 8    # 连接池中的最大空闲连接
spring.redis.jedis.pool.min-idle: 0    # 连接池中的最小空闲连接
spring.redis.jedis.pool.time-between-eviction-runs: -1ms # 空闲连接扫描间隔时间, 扫描到空闲连接则关闭连接
################################################## Redis 配置 ##################################################
