ahao:
  web:
    upload:
      profile: local # 上传环境, local上传到本机, remote上传到远程服务器
      file-save-uri: d:/tmp/        # 文件上传uri(不配置的话为java.io.tmpdir目录), 推荐设置绝对路径
      file-prefix-uri: /UploadFile/ # 文件上传返回的路径, 用于外部用户访问文件

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.137:3306/db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: root
  redis:
    host: 192.168.153.137
    port: 6379
#    password:
    redisson:
      file: classpath:redisson-single.yaml
